[SERVICE]
    Flush        1
    Log_Level    warn
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224

[FILTER]
    Name   grep
    Match  *
    Regex  log .*"match":.*

[OUTPUT]
    Name         http
    Match        *
    Host         backend
    Port         8080
    URI          /api/ingest
    Format       json
    json_date_key false
    Retry_Limit  5
