package api

import (
	"net/http"
)

// CRSRule represents a single OWASP CRS v4 rule.
type CRSRule struct {
	ID            int    `json:"id"`
	Msg           string `json:"msg"`
	ParanoiaLevel int    `json:"paranoia_level"`
	Tag           string `json:"tag"`
	Severity      string `json:"severity"`
}

// crsCatalog — vollständiger OWASP CRS v4 Katalog (341 Rules mit attack-tags)
var crsCatalog = []CRSRule{
	{ID: 911100, Msg: "Method is not allowed by policy", ParanoiaLevel: 1, Tag: "attack-generic", Severity: "critical"},
	{ID: 913100, Msg: "Found User-Agent associated with security scanner", ParanoiaLevel: 1, Tag: "attack-reputation-scanner", Severity: "critical"},
	{ID: 920100, Msg: "Invalid HTTP Request Line", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920120, Msg: "Attempted multipart/form-data bypass", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920121, Msg: "Attempted multipart/form-data bypass", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920160, Msg: "Content-Length HTTP header is not numeric", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920170, Msg: "GET or HEAD Request with Body Content", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920171, Msg: "GET or HEAD Request with Transfer-Encoding", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920180, Msg: "POST without Content-Length and Transfer-Encoding headers", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920181, Msg: "Content-Length and Transfer-Encoding headers present", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920190, Msg: "Range: Invalid Last Byte Value", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920200, Msg: "Range: Too many fields (6 or more)", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920201, Msg: "Range: Too many fields for pdf request (63 or more)", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920202, Msg: "Range: Too many fields for pdf request (6 or more)", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920210, Msg: "Multiple/Conflicting Connection Header Data Found", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920230, Msg: "Multiple URL Encoding Detected", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920240, Msg: "URL Encoding Abuse Attack Attempt", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920250, Msg: "UTF8 Encoding Abuse Attack Attempt", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920260, Msg: "Unicode Full/Half Width Abuse Attack Attempt", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920270, Msg: "Invalid character in request (null character)", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920271, Msg: "Invalid character in request (non printable characters)", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920272, Msg: "Invalid character in request (outside of printable chars below ascii 127)", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920273, Msg: "Invalid character in request (outside of very strict set)", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920274, Msg: "Invalid character in request headers (outside of very strict set)", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920275, Msg: "Invalid character in request headers (outside of very strict set)", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920280, Msg: "Request Missing a Host Header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920290, Msg: "Empty Host Header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920300, Msg: "Request Missing an Accept Header", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "notice"},
	{ID: 920310, Msg: "Request Has an Empty Accept Header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "notice"},
	{ID: 920311, Msg: "Request Has an Empty Accept Header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "notice"},
	{ID: 920320, Msg: "Missing User Agent Header", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "notice"},
	{ID: 920330, Msg: "Empty User Agent Header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "notice"},
	{ID: 920340, Msg: "Content-Type header missing from request with non-zero Content-Length", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920350, Msg: "Host header is a numeric IP address", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 920360, Msg: "Argument name too long", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920370, Msg: "Argument value too long", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920380, Msg: "Too many arguments in request", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920390, Msg: "Total arguments size exceeded", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920400, Msg: "Uploaded file size too large", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920410, Msg: "Total uploaded files size too large", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920420, Msg: "Request content type is not allowed by policy", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920430, Msg: "HTTP protocol version is not allowed by policy", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920440, Msg: "URL file extension is restricted by policy", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920450, Msg: "HTTP header is restricted by policy", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920451, Msg: "HTTP header is restricted by policy", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920460, Msg: "Abnormal character escapes in request", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920470, Msg: "Illegal Content-Type header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920480, Msg: "Request content type charset is not allowed by policy", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920490, Msg: "Request header x-up-devcap-post-charset detected", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920500, Msg: "Attempt to access a backup or working file", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920510, Msg: "Invalid Cache-Control request header", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920520, Msg: "Accept-Encoding header exceeded sensible length", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920521, Msg: "Illegal Accept-Encoding header", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920530, Msg: "Multiple charsets detected in content type header", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920540, Msg: "Possible Unicode character bypass detected", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920600, Msg: "Illegal Accept header: charset parameter", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920610, Msg: "Raw (unencoded) fragment in request URI", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920620, Msg: "Multiple Content-Type Request Headers", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920640, Msg: "Content-Type header missing from request with body", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920650, Msg: "HTTP method override attempt via _method parameter", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 920660, Msg: "Obsolete Request-Range header detected", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "warning"},
	{ID: 921110, Msg: "HTTP Request Smuggling Attack", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921120, Msg: "HTTP Response Splitting Attack", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921130, Msg: "HTTP Response Splitting Attack", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921140, Msg: "HTTP Header Injection Attack via headers", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921150, Msg: "HTTP Header Injection Attack via payload (CR/LF detected)", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921151, Msg: "HTTP Header Injection Attack via payload (CR/LF detected)", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921160, Msg: "HTTP Header Injection Attack via payload (CR/LF and header-name detected)", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921180, Msg: "HTTP Parameter Pollution", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921190, Msg: "HTTP Splitting (CR/LF in request filename detected)", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921210, Msg: "HTTP Parameter Pollution after detecting bogus char after parameter array", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921220, Msg: "HTTP Parameter Pollution possible via array notation", ParanoiaLevel: 4, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921230, Msg: "HTTP Range Header detected", ParanoiaLevel: 3, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921240, Msg: "mod_proxy attack attempt detected", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921250, Msg: "Old Cookies V1 usage attempt detected", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921421, Msg: "Content-Type header: Dangerous content type outside mime type declaration", ParanoiaLevel: 1, Tag: "attack-protocol", Severity: "critical"},
	{ID: 921422, Msg: "Content-Type header: Dangerous content type outside mime type declaration", ParanoiaLevel: 2, Tag: "attack-protocol", Severity: "critical"},
	{ID: 922100, Msg: "Multipart content type global _charset_ definition is not allowed by policy", ParanoiaLevel: 1, Tag: "attack-multipart-header", Severity: "critical"},
	{ID: 922110, Msg: "Illegal MIME Multipart Header content-type: charset parameter", ParanoiaLevel: 1, Tag: "attack-multipart-header", Severity: "critical"},
	{ID: 922120, Msg: "Content-Transfer-Encoding deprecated and should not be used", ParanoiaLevel: 1, Tag: "attack-multipart-header", Severity: "critical"},
	{ID: 922130, Msg: "Multipart header contains characters outside of valid range", ParanoiaLevel: 1, Tag: "attack-multipart-header", Severity: "critical"},
	{ID: 930100, Msg: "Path Traversal Attack (/../) or (/.../) ", ParanoiaLevel: 1, Tag: "attack-lfi", Severity: "critical"},
	{ID: 930110, Msg: "Path Traversal Attack (/../) or (/.../)", ParanoiaLevel: 1, Tag: "attack-lfi", Severity: "critical"},
	{ID: 930120, Msg: "OS File Access Attempt", ParanoiaLevel: 1, Tag: "attack-lfi", Severity: "critical"},
	{ID: 930121, Msg: "OS File Access Attempt in REQUEST_HEADERS", ParanoiaLevel: 2, Tag: "attack-lfi", Severity: "critical"},
	{ID: 930130, Msg: "Restricted File Access Attempt", ParanoiaLevel: 1, Tag: "attack-lfi", Severity: "critical"},
	{ID: 930140, Msg: "Restricted File Access Attempt: AI Coding Assistant Artifact", ParanoiaLevel: 1, Tag: "attack-lfi", Severity: "critical"},
	{ID: 931100, Msg: "Possible Remote File Inclusion (RFI) Attack: URL Parameter using IP Address", ParanoiaLevel: 1, Tag: "attack-rfi", Severity: "critical"},
	{ID: 931110, Msg: "Possible Remote File Inclusion (RFI) Attack: Common RFI Vulnerable Parameter Name used w/URL Payload", ParanoiaLevel: 1, Tag: "attack-rfi", Severity: "critical"},
	{ID: 931120, Msg: "Possible Remote File Inclusion (RFI) Attack: URL Payload Used w/Trailing Question Mark Character (?)", ParanoiaLevel: 1, Tag: "attack-rfi", Severity: "critical"},
	{ID: 931130, Msg: "Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link", ParanoiaLevel: 2, Tag: "attack-rfi", Severity: "critical"},
	{ID: 931131, Msg: "Possible Remote File Inclusion (RFI) Attack", ParanoiaLevel: 2, Tag: "attack-rfi", Severity: "critical"},
	{ID: 932120, Msg: "Remote Command Execution: Windows PowerShell Command Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932125, Msg: "Remote Command Execution: Windows Powershell Alias Command Injection", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932130, Msg: "Remote Command Execution: Unix Shell Expression Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932131, Msg: "Remote Command Execution: Unix Shell Expression Found", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932140, Msg: "Remote Command Execution: Windows FOR/IF Command Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932160, Msg: "Remote Command Execution: Unix Shell Code Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932161, Msg: "Remote Command Execution: Unix Shell Code Found in REQUEST_HEADERS", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932170, Msg: "Remote Command Execution: Shellshock (CVE-2014-6271)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932171, Msg: "Remote Command Execution: Shellshock (CVE-2014-6271)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932175, Msg: "Remote Command Execution: Unix shell alias invocation", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932180, Msg: "Restricted File Upload Attempt", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932190, Msg: "Remote Command Execution: Wildcard bypass technique attempt", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932200, Msg: "RCE Bypass Technique", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932205, Msg: "RCE Bypass Technique", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932206, Msg: "RCE Bypass Technique", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932207, Msg: "RCE Bypass Technique", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932210, Msg: "Remote Command Execution: SQLite System Command Execution", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932220, Msg: "Remote Command Execution: Unix Command Injection with pipe", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932230, Msg: "Remote Command Execution: Unix Command Injection (2-3 chars)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932231, Msg: "Remote Command Execution: Unix Command Injection", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932232, Msg: "Remote Command Execution: Unix Command Injection", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932235, Msg: "Remote Command Execution: Unix Command Injection (command without evasion)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932236, Msg: "Remote Command Execution: Unix Command Injection (command without evasion)", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932237, Msg: "Remote Command Execution: Unix Shell Code Found in REQUEST_HEADERS", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932238, Msg: "Remote Command Execution: Unix Shell Code Found in REQUEST_HEADERS", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932239, Msg: "Remote Command Execution: Unix Command Injection found in user-agent or referer header", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932240, Msg: "Remote Command Execution: Unix Command Injection evasion attempt detected", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932250, Msg: "Remote Command Execution: Direct Unix Command Execution", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932260, Msg: "Remote Command Execution: Direct Unix Command Execution", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932270, Msg: "Remote Command Execution: Unix Shell Expression Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932271, Msg: "Remote Command Execution: Unix Shell Expression Found", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932280, Msg: "Remote Command Execution: Brace Expansion Found", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932281, Msg: "Remote Command Execution: Brace Expansion Found", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932300, Msg: "Remote Command Execution: SMTP Command Execution", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932301, Msg: "Remote Command Execution: SMTP Command Execution", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932310, Msg: "Remote Command Execution: IMAP Command Execution", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932311, Msg: "Remote Command Execution: IMAP Command Execution", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932320, Msg: "Remote Command Execution: POP3 Command Execution", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932321, Msg: "Remote Command Execution: POP3 Command Execution", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932330, Msg: "Remote Command Execution: Unix shell history invocation", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932331, Msg: "Remote Command Execution: Unix shell history invocation", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932340, Msg: "Remote Command Execution: Direct Unix Command Execution (No Arguments)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932350, Msg: "Remote Command Execution: Direct Unix Command Execution (No Arguments)", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 932370, Msg: "Remote Command Execution: Windows Command Injection", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932371, Msg: "Remote Command Execution: Windows Command Injection", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 932380, Msg: "Remote Command Execution: Windows Command Injection", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 932390, Msg: "Remote Command Execution: Shell Fork Bomb", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 933100, Msg: "PHP Injection Attack: PHP Open Tag Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933110, Msg: "PHP Injection Attack: PHP Script File Upload Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933111, Msg: "PHP Injection Attack: PHP Script File Upload Found", ParanoiaLevel: 3, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933120, Msg: "PHP Injection Attack: Configuration Directive Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933130, Msg: "PHP Injection Attack: Variables Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933131, Msg: "PHP Injection Attack: Variables Found", ParanoiaLevel: 3, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933135, Msg: "PHP Injection Attack: Variable Access Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933140, Msg: "PHP Injection Attack: I/O Stream Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933150, Msg: "PHP Injection Attack: High-Risk PHP Function Name Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933151, Msg: "PHP Injection Attack: Medium-Risk PHP Function Name Found", ParanoiaLevel: 2, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933152, Msg: "PHP Injection Attack: Medium-Risk PHP Function Name Found", ParanoiaLevel: 2, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933153, Msg: "PHP Injection Attack: Medium-Risk PHP Function Name Found", ParanoiaLevel: 2, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933160, Msg: "PHP Injection Attack: High-Risk PHP Function Call Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933161, Msg: "PHP Injection Attack: Low-Value PHP Function Call Found", ParanoiaLevel: 3, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933170, Msg: "PHP Injection Attack: Serialized Object Injection", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933180, Msg: "PHP Injection Attack: Variable Function Call Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933190, Msg: "PHP Injection Attack: PHP Closing Tag Found", ParanoiaLevel: 3, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933200, Msg: "PHP Injection Attack: Wrapper scheme detected", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933210, Msg: "PHP Injection Attack: Variable Function Call Found", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933211, Msg: "PHP Injection Attack: Variable Function Call Found", ParanoiaLevel: 3, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 933220, Msg: "PHP Injection Attack: PHP Session File Upload Attempt", ParanoiaLevel: 1, Tag: "attack-injection-php", Severity: "critical"},
	{ID: 934100, Msg: "Node.js Injection Attack 1/2", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 934101, Msg: "Node.js Injection Attack 2/2", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 934110, Msg: "Possible Server Side Request Forgery (SSRF) Attack: Cloud provider metadata URL in Parameter", ParanoiaLevel: 1, Tag: "attack-ssrf", Severity: "critical"},
	{ID: 934120, Msg: "Possible Server Side Request Forgery (SSRF) Attack: URL Parameter using IP Address", ParanoiaLevel: 2, Tag: "attack-ssrf", Severity: "critical"},
	{ID: 934130, Msg: "JavaScript Prototype Pollution", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 934140, Msg: "Perl Injection Attack", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 934150, Msg: "Ruby Injection Attack", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 934160, Msg: "Node.js DoS attack", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 934170, Msg: "PHP data scheme attack", ParanoiaLevel: 1, Tag: "attack-ssrf", Severity: "critical"},
	{ID: 934180, Msg: "SSTI Attack", ParanoiaLevel: 2, Tag: "attack-ssti", Severity: "critical"},
	{ID: 934190, Msg: "Possible SSRF Attack: Scheme-less localhost or internal hostname detected", ParanoiaLevel: 1, Tag: "attack-ssrf", Severity: "critical"},
	{ID: 934200, Msg: "Server-Side Template Injection (SSTI) Attack", ParanoiaLevel: 1, Tag: "attack-ssti", Severity: "critical"},
	{ID: 941100, Msg: "XSS Attack Detected via libinjection", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941101, Msg: "XSS Attack Detected via libinjection", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941110, Msg: "XSS Filter - Category 1: Script Tag Vector", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941120, Msg: "XSS Filter - Category 2: Event Handler Vector", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941130, Msg: "XSS Filter - Category 3: Attribute Vector", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941140, Msg: "XSS Filter - Category 4: Javascript URI Vector", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941150, Msg: "XSS Filter - Category 5: Disallowed HTML Attributes", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941160, Msg: "NoScript XSS InjectionChecker: HTML Injection", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941170, Msg: "NoScript XSS InjectionChecker: Attribute Injection", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941180, Msg: "Node-Validator Deny List Keywords", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941181, Msg: "Node-Validator Deny List Keywords", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941190, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941200, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941210, Msg: "Javascript Word Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941220, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941230, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941240, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941250, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941260, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941270, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941280, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941290, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941300, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941310, Msg: "US-ASCII Malformed Encoding XSS Filter - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941320, Msg: "Possible XSS Attack Detected - HTML Tag Handler", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941330, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941340, Msg: "IE XSS Filters - Attack Detected", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941350, Msg: "UTF-7 Encoding IE XSS - Attack Detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941360, Msg: "JSFuck / Hieroglyphy obfuscation detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941370, Msg: "JavaScript global variable found", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941380, Msg: "AngularJS client side template injection detected", ParanoiaLevel: 2, Tag: "attack-xss", Severity: "critical"},
	{ID: 941390, Msg: "Javascript method detected", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 941400, Msg: "XSS JavaScript function without parentheses", ParanoiaLevel: 1, Tag: "attack-xss", Severity: "critical"},
	{ID: 942100, Msg: "SQL Injection Attack Detected via libinjection", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942101, Msg: "SQL Injection Attack Detected via libinjection", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942120, Msg: "SQL Injection Attack: SQL Operator Detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942130, Msg: "SQL Injection Attack: SQL Boolean-based attack detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942131, Msg: "SQL Injection Attack: SQL Boolean-based attack detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942140, Msg: "SQL Injection Attack: Common DB Names Detected", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942150, Msg: "SQL Injection Attack: SQL function name detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942151, Msg: "SQL Injection Attack: SQL function name detected", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942152, Msg: "SQL Injection Attack: SQL function name detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942160, Msg: "Detects blind sqli tests using sleep() or benchmark()", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942170, Msg: "Detects SQL benchmark and sleep injection attempts including conditional queries", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942180, Msg: "Detects basic SQL authentication bypass attempts 1/3", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942190, Msg: "Detects MSSQL code execution and information gathering attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942200, Msg: "Detects MySQL comment-/space-obfuscated injections and backtick termination", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942210, Msg: "Detects chained SQL injection attempts 1/2", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942220, Msg: "Looking for integer overflow attacks", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942230, Msg: "Detects conditional SQL injection attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942240, Msg: "Detects MySQL charset switch and MSSQL DoS attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942250, Msg: "Detects MATCH AGAINST, MERGE and EXECUTE IMMEDIATE injections", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942251, Msg: "Detects HAVING injections", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942260, Msg: "Detects basic SQL authentication bypass attempts 2/3", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942270, Msg: "Looking for basic sql injection. Common attack string for mysql, oracle and others", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942280, Msg: "Detects Postgres pg_sleep injection, waitfor delay attacks and database shutdown attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942290, Msg: "Finds basic MongoDB SQL injection attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942300, Msg: "Detects MySQL comments, conditions and ch(a)r injections", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942310, Msg: "Detects chained SQL injection attempts 2/2", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942320, Msg: "Detects MySQL and PostgreSQL stored procedure/function injections", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942321, Msg: "Detects MySQL and PostgreSQL stored procedure/function injections", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942330, Msg: "Detects classic SQL injection probings 1/3", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942340, Msg: "Detects basic SQL authentication bypass attempts 3/3", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942350, Msg: "Detects MySQL UDF injection and other data/structure manipulation attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942360, Msg: "Detects concatenated basic SQL injection and SQLLFI attempts", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942361, Msg: "Detects basic SQL injection based on keyword alter or union", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942362, Msg: "Detects concatenated basic SQL injection and SQLLFI attempts", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942370, Msg: "Detects classic SQL injection probings 2/3", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942380, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942390, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942400, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942410, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942420, Msg: "Restricted SQL Character Anomaly Detection (cookies): # of special characters exceeded (8)", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942421, Msg: "Restricted SQL Character Anomaly Detection (cookies): # of special characters exceeded (3)", ParanoiaLevel: 4, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942430, Msg: "Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942431, Msg: "Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942432, Msg: "Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)", ParanoiaLevel: 4, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942440, Msg: "SQL Comment Sequence Detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942450, Msg: "SQL Bin or Hex Encoding Identified", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942460, Msg: "Meta-Character Anomaly Detection Alert - Repetitive Non-Word Characters", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "warning"},
	{ID: 942470, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942480, Msg: "SQL Injection Attack", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942490, Msg: "Detects classic SQL injection probings 3/3", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942500, Msg: "MySQL in-line comment detected", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942510, Msg: "SQLi bypass attempt by ticks or backticks detected", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942511, Msg: "SQLi bypass attempt by ticks detected", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942520, Msg: "Detects basic SQL authentication bypass attempts 4.0/4", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942521, Msg: "Detects basic SQL authentication bypass attempts 4.1/4", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942522, Msg: "Detects basic SQL authentication bypass attempts 4.1/4", ParanoiaLevel: 2, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942530, Msg: "SQLi query termination detected", ParanoiaLevel: 3, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942540, Msg: "SQL Authentication bypass (split query)", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942550, Msg: "JSON-Based SQL Injection", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 942560, Msg: "MySQL Scientific Notation payload detected", ParanoiaLevel: 1, Tag: "attack-sqli", Severity: "critical"},
	{ID: 943100, Msg: "Possible Session Fixation Attack: Setting Cookie Values in HTML", ParanoiaLevel: 1, Tag: "attack-fixation", Severity: "critical"},
	{ID: 943110, Msg: "Possible Session Fixation Attack: SessionID Parameter Name with Off-Domain Referer", ParanoiaLevel: 1, Tag: "attack-fixation", Severity: "critical"},
	{ID: 943120, Msg: "Possible Session Fixation Attack: SessionID Parameter Name with No Referer", ParanoiaLevel: 1, Tag: "attack-fixation", Severity: "critical"},
	{ID: 944100, Msg: "Remote Command Execution: Suspicious Java class detected", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 944110, Msg: "Remote Command Execution: Java process spawn (CVE-2017-9805)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 944120, Msg: "Remote Command Execution: Java serialization (CVE-2015-4852)", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 944130, Msg: "Suspicious Java class detected", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 944140, Msg: "Java Injection Attack: Java Script File Upload Found", ParanoiaLevel: 1, Tag: "attack-injection-java", Severity: "critical"},
	{ID: 944150, Msg: "Potential Remote Command Execution: Log4j / Log4shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 944151, Msg: "Potential Remote Command Execution: Log4j / Log4shell", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944152, Msg: "Potential Remote Command Execution: Log4j / Log4shell", ParanoiaLevel: 4, Tag: "attack-rce", Severity: "critical"},
	{ID: 944200, Msg: "Magic bytes Detected, probable java serialization in use", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944210, Msg: "Magic bytes Detected Base64 Encoded, probable java serialization in use", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944240, Msg: "Remote Command Execution: Java serialization (CVE-2015-4852)", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944250, Msg: "Remote Command Execution: Suspicious Java method detected", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944260, Msg: "Remote Command Execution: Malicious class-loading payload", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 944300, Msg: "Base64 encoded string matched suspicious keyword", ParanoiaLevel: 3, Tag: "attack-rce", Severity: "critical"},
	{ID: 950100, Msg: "The Application Returned a 500-Level Status Code", ParanoiaLevel: 2, Tag: "attack-disclosure", Severity: "error"},
	{ID: 950130, Msg: "Directory Listing", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 950140, Msg: "CGI source code leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 950150, Msg: "ASP.NET exception leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 951110, Msg: "Microsoft Access SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951120, Msg: "Oracle SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951130, Msg: "DB2 SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951140, Msg: "EMC SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951150, Msg: "firebird SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951160, Msg: "Frontbase SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951170, Msg: "hsqldb SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951180, Msg: "informix SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951190, Msg: "ingres SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951200, Msg: "interbase SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951210, Msg: "maxDB SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951220, Msg: "mssql SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951230, Msg: "mysql SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951240, Msg: "postgres SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951250, Msg: "sqlite SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 951260, Msg: "Sybase SQL Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "critical"},
	{ID: 952110, Msg: "Java Errors", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 953100, Msg: "PHP Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 953101, Msg: "PHP Information Leakage", ParanoiaLevel: 2, Tag: "attack-disclosure", Severity: "error"},
	{ID: 953110, Msg: "PHP source code leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 953120, Msg: "PHP source code leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 954100, Msg: "Disclosure of IIS install location", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 954101, Msg: "Disclosure of IIS install location", ParanoiaLevel: 2, Tag: "attack-disclosure", Severity: "error"},
	{ID: 954110, Msg: "Application Availability Error", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 954120, Msg: "IIS Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 954130, Msg: "IIS Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 955100, Msg: "PHP Web shell detected", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955110, Msg: "r57 web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955120, Msg: "WSO web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955130, Msg: "b4tm4n web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955140, Msg: "Mini Shell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955150, Msg: "Ashiyane web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955160, Msg: "Symlink_Sa web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955170, Msg: "CasuS web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955180, Msg: "GRP WebShell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955190, Msg: "NGHshell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955200, Msg: "SimAttacker web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955210, Msg: "Unknown web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955220, Msg: "Unknown web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955230, Msg: "lostDC web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955240, Msg: "Unknown web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955250, Msg: "Unknown web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955260, Msg: "Ru24PostWebShell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955270, Msg: "s72 Shell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955280, Msg: "PhpSpy web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955290, Msg: "g00nshell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955300, Msg: "PuNkHoLic shell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955310, Msg: "azrail web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955320, Msg: "SmEvK_PaThAn Shell web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955330, Msg: "Shell I web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955340, Msg: "b374k m1n1 web shell", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 955350, Msg: "webadmin.php file manager", ParanoiaLevel: 2, Tag: "attack-rce", Severity: "critical"},
	{ID: 955400, Msg: "ASP Web shell detected", ParanoiaLevel: 1, Tag: "attack-rce", Severity: "critical"},
	{ID: 956100, Msg: "RUBY Information Leakage", ParanoiaLevel: 1, Tag: "attack-disclosure", Severity: "error"},
	{ID: 956110, Msg: "Ruby source code leakage", ParanoiaLevel: 2, Tag: "attack-disclosure", Severity: "error"},
}

// GetRuleCatalog returns all CRS rules as JSON
func (h *Handler) GetRuleCatalog(w http.ResponseWriter, r *http.Request) {
	jsonOK(w, crsCatalog)
}
